// Code generated by internal/codegen/domainadapter. DO NOT EDIT.

package handler

import (
	"context"

	"github.com/go-chi/chi/v5"
	"github.com/meridian-labs/meridian/internal/generated/api/asset"
	"github.com/meridian-labs/meridian/internal/generated/api/auth"
	"github.com/meridian-labs/meridian/internal/generated/api/collaboration"
	"github.com/meridian-labs/meridian/internal/generated/api/diff"
	"github.com/meridian-labs/meridian/internal/generated/api/job"
	"github.com/meridian-labs/meridian/internal/generated/api/layer"
	"github.com/meridian-labs/meridian/internal/generated/api/platform"
	"github.com/meridian-labs/meridian/internal/generated/api/repository"
	serviceapi "github.com/meridian-labs/meridian/internal/generated/api/service"
	"github.com/meridian-labs/meridian/internal/generated/api/system"
	"github.com/meridian-labs/meridian/internal/generated/api/tenant"
	"github.com/meridian-labs/meridian/internal/generated/api/view"
)

type assetServer struct {
	asset.UnimplementedStrictServer
	server *Server
}

// CreateSourceSpec 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) CreateSourceSpec(ctx context.Context, request asset.CreateSourceSpecRequestObject) (asset.CreateSourceSpecResponseObject, error) {
	return adapter.server.CreateSourceSpec(ctx, request)
}

// DeleteSourceSpec 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) DeleteSourceSpec(ctx context.Context, request asset.DeleteSourceSpecRequestObject) (asset.DeleteSourceSpecResponseObject, error) {
	return adapter.server.DeleteSourceSpec(ctx, request)
}

// DeprecateAssetVersion 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) DeprecateAssetVersion(ctx context.Context, request asset.DeprecateAssetVersionRequestObject) (asset.DeprecateAssetVersionResponseObject, error) {
	return adapter.server.DeprecateAssetVersion(ctx, request)
}

// GenerateAssetWithAi 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) GenerateAssetWithAi(ctx context.Context, request asset.GenerateAssetWithAiRequestObject) (asset.GenerateAssetWithAiResponseObject, error) {
	return adapter.server.GenerateAssetWithAi(ctx, request)
}

// GenerateMissingAssetWithAi 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) GenerateMissingAssetWithAi(ctx context.Context, request asset.GenerateMissingAssetWithAiRequestObject) (asset.GenerateMissingAssetWithAiResponseObject, error) {
	return adapter.server.GenerateMissingAssetWithAi(ctx, request)
}

// GetAsset 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) GetAsset(ctx context.Context, request asset.GetAssetRequestObject) (asset.GetAssetResponseObject, error) {
	return adapter.server.GetAsset(ctx, request)
}

// GetAssetVersion 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) GetAssetVersion(ctx context.Context, request asset.GetAssetVersionRequestObject) (asset.GetAssetVersionResponseObject, error) {
	return adapter.server.GetAssetVersion(ctx, request)
}

// GetAssetVersionProvenance 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) GetAssetVersionProvenance(ctx context.Context, request asset.GetAssetVersionProvenanceRequestObject) (asset.GetAssetVersionProvenanceResponseObject, error) {
	return adapter.server.GetAssetVersionProvenance(ctx, request)
}

// GetPublicAsset 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) GetPublicAsset(ctx context.Context, request asset.GetPublicAssetRequestObject) (asset.GetPublicAssetResponseObject, error) {
	return adapter.server.GetPublicAsset(ctx, request)
}

// ListAssetKinds 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) ListAssetKinds(ctx context.Context, request asset.ListAssetKindsRequestObject) (asset.ListAssetKindsResponseObject, error) {
	return adapter.server.ListAssetKinds(ctx, request)
}

// ListAssetVersionItems 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) ListAssetVersionItems(ctx context.Context, request asset.ListAssetVersionItemsRequestObject) (asset.ListAssetVersionItemsResponseObject, error) {
	return adapter.server.ListAssetVersionItems(ctx, request)
}

// ListAssetVersions 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) ListAssetVersions(ctx context.Context, request asset.ListAssetVersionsRequestObject) (asset.ListAssetVersionsResponseObject, error) {
	return adapter.server.ListAssetVersions(ctx, request)
}

// ListSourceBindings 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) ListSourceBindings(ctx context.Context, request asset.ListSourceBindingsRequestObject) (asset.ListSourceBindingsResponseObject, error) {
	return adapter.server.ListSourceBindings(ctx, request)
}

// ListSourceSpecs 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) ListSourceSpecs(ctx context.Context, request asset.ListSourceSpecsRequestObject) (asset.ListSourceSpecsResponseObject, error) {
	return adapter.server.ListSourceSpecs(ctx, request)
}

// PreviewMerge 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) PreviewMerge(ctx context.Context, request asset.PreviewMergeRequestObject) (asset.PreviewMergeResponseObject, error) {
	return adapter.server.PreviewMerge(ctx, request)
}

// ProduceSource 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) ProduceSource(ctx context.Context, request asset.ProduceSourceRequestObject) (asset.ProduceSourceResponseObject, error) {
	return adapter.server.ProduceSource(ctx, request)
}

// PublishAssetVersion 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) PublishAssetVersion(ctx context.Context, request asset.PublishAssetVersionRequestObject) (asset.PublishAssetVersionResponseObject, error) {
	return adapter.server.PublishAssetVersion(ctx, request)
}

// PushAssetRevision 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) PushAssetRevision(ctx context.Context, request asset.PushAssetRevisionRequestObject) (asset.PushAssetRevisionResponseObject, error) {
	return adapter.server.PushAssetRevision(ctx, request)
}

// RetireAssetVersion 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) RetireAssetVersion(ctx context.Context, request asset.RetireAssetVersionRequestObject) (asset.RetireAssetVersionResponseObject, error) {
	return adapter.server.RetireAssetVersion(ctx, request)
}

// UpdateAssetKindState 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) UpdateAssetKindState(ctx context.Context, request asset.UpdateAssetKindStateRequestObject) (asset.UpdateAssetKindStateResponseObject, error) {
	return adapter.server.UpdateAssetKindState(ctx, request)
}

// UpdateSourceSpec 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) UpdateSourceSpec(ctx context.Context, request asset.UpdateSourceSpecRequestObject) (asset.UpdateSourceSpecResponseObject, error) {
	return adapter.server.UpdateSourceSpec(ctx, request)
}

type authServer struct {
	auth.UnimplementedStrictServer
	server *Server
}

// GetMe 将 auth 的严格操作委托给对应的 Handler 实现。
func (adapter authServer) GetMe(ctx context.Context, request auth.GetMeRequestObject) (auth.GetMeResponseObject, error) {
	return adapter.server.GetMe(ctx, request)
}

// GetMyPreferences 将 auth 的严格操作委托给对应的 Handler 实现。
func (adapter authServer) GetMyPreferences(ctx context.Context, request auth.GetMyPreferencesRequestObject) (auth.GetMyPreferencesResponseObject, error) {
	return adapter.server.GetMyPreferences(ctx, request)
}

// Login 将 auth 的严格操作委托给对应的 Handler 实现。
func (adapter authServer) Login(ctx context.Context, request auth.LoginRequestObject) (auth.LoginResponseObject, error) {
	return adapter.server.Login(ctx, request)
}

// Logout 将 auth 的严格操作委托给对应的 Handler 实现。
func (adapter authServer) Logout(ctx context.Context, request auth.LogoutRequestObject) (auth.LogoutResponseObject, error) {
	return adapter.server.Logout(ctx, request)
}

// Refresh 将 auth 的严格操作委托给对应的 Handler 实现。
func (adapter authServer) Refresh(ctx context.Context, request auth.RefreshRequestObject) (auth.RefreshResponseObject, error) {
	return adapter.server.Refresh(ctx, request)
}

// UpdateMyPreferences 将 auth 的严格操作委托给对应的 Handler 实现。
func (adapter authServer) UpdateMyPreferences(ctx context.Context, request auth.UpdateMyPreferencesRequestObject) (auth.UpdateMyPreferencesResponseObject, error) {
	return adapter.server.UpdateMyPreferences(ctx, request)
}

type collaborationServer struct {
	collaboration.UnimplementedStrictServer
	server *Server
}

// AcknowledgeBreakingTodo 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) AcknowledgeBreakingTodo(ctx context.Context, request collaboration.AcknowledgeBreakingTodoRequestObject) (collaboration.AcknowledgeBreakingTodoResponseObject, error) {
	return adapter.server.AcknowledgeBreakingTodo(ctx, request)
}

// CreateNotificationChannel 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) CreateNotificationChannel(ctx context.Context, request collaboration.CreateNotificationChannelRequestObject) (collaboration.CreateNotificationChannelResponseObject, error) {
	return adapter.server.CreateNotificationChannel(ctx, request)
}

// CreateServiceComment 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) CreateServiceComment(ctx context.Context, request collaboration.CreateServiceCommentRequestObject) (collaboration.CreateServiceCommentResponseObject, error) {
	return adapter.server.CreateServiceComment(ctx, request)
}

// DeleteNotificationChannel 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) DeleteNotificationChannel(ctx context.Context, request collaboration.DeleteNotificationChannelRequestObject) (collaboration.DeleteNotificationChannelResponseObject, error) {
	return adapter.server.DeleteNotificationChannel(ctx, request)
}

// ListAuditLogs 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) ListAuditLogs(ctx context.Context, request collaboration.ListAuditLogsRequestObject) (collaboration.ListAuditLogsResponseObject, error) {
	return adapter.server.ListAuditLogs(ctx, request)
}

// ListBreakingTodos 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) ListBreakingTodos(ctx context.Context, request collaboration.ListBreakingTodosRequestObject) (collaboration.ListBreakingTodosResponseObject, error) {
	return adapter.server.ListBreakingTodos(ctx, request)
}

// ListNotificationChannels 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) ListNotificationChannels(ctx context.Context, request collaboration.ListNotificationChannelsRequestObject) (collaboration.ListNotificationChannelsResponseObject, error) {
	return adapter.server.ListNotificationChannels(ctx, request)
}

// ListNotifications 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) ListNotifications(ctx context.Context, request collaboration.ListNotificationsRequestObject) (collaboration.ListNotificationsResponseObject, error) {
	return adapter.server.ListNotifications(ctx, request)
}

// ListServiceComments 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) ListServiceComments(ctx context.Context, request collaboration.ListServiceCommentsRequestObject) (collaboration.ListServiceCommentsResponseObject, error) {
	return adapter.server.ListServiceComments(ctx, request)
}

// ListSubscriptions 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) ListSubscriptions(ctx context.Context, request collaboration.ListSubscriptionsRequestObject) (collaboration.ListSubscriptionsResponseObject, error) {
	return adapter.server.ListSubscriptions(ctx, request)
}

// MarkAllNotificationsRead 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) MarkAllNotificationsRead(ctx context.Context, request collaboration.MarkAllNotificationsReadRequestObject) (collaboration.MarkAllNotificationsReadResponseObject, error) {
	return adapter.server.MarkAllNotificationsRead(ctx, request)
}

// MarkNotificationRead 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) MarkNotificationRead(ctx context.Context, request collaboration.MarkNotificationReadRequestObject) (collaboration.MarkNotificationReadResponseObject, error) {
	return adapter.server.MarkNotificationRead(ctx, request)
}

// PutSubscription 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) PutSubscription(ctx context.Context, request collaboration.PutSubscriptionRequestObject) (collaboration.PutSubscriptionResponseObject, error) {
	return adapter.server.PutSubscription(ctx, request)
}

// RotateNotificationChannelSecret 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) RotateNotificationChannelSecret(ctx context.Context, request collaboration.RotateNotificationChannelSecretRequestObject) (collaboration.RotateNotificationChannelSecretResponseObject, error) {
	return adapter.server.RotateNotificationChannelSecret(ctx, request)
}

// TestNotificationChannel 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) TestNotificationChannel(ctx context.Context, request collaboration.TestNotificationChannelRequestObject) (collaboration.TestNotificationChannelResponseObject, error) {
	return adapter.server.TestNotificationChannel(ctx, request)
}

// UpdateNotificationChannel 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) UpdateNotificationChannel(ctx context.Context, request collaboration.UpdateNotificationChannelRequestObject) (collaboration.UpdateNotificationChannelResponseObject, error) {
	return adapter.server.UpdateNotificationChannel(ctx, request)
}

type diffServer struct {
	diff.UnimplementedStrictServer
	server *Server
}

// CreateDiffRuleSet 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) CreateDiffRuleSet(ctx context.Context, request diff.CreateDiffRuleSetRequestObject) (diff.CreateDiffRuleSetResponseObject, error) {
	return adapter.server.CreateDiffRuleSet(ctx, request)
}

// CreateDiffSnapshotShareLink 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) CreateDiffSnapshotShareLink(ctx context.Context, request diff.CreateDiffSnapshotShareLinkRequestObject) (diff.CreateDiffSnapshotShareLinkResponseObject, error) {
	return adapter.server.CreateDiffSnapshotShareLink(ctx, request)
}

// CreateDiffUpload 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) CreateDiffUpload(ctx context.Context, request diff.CreateDiffUploadRequestObject) (diff.CreateDiffUploadResponseObject, error) {
	return adapter.server.CreateDiffUpload(ctx, request)
}

// DeleteDiffRuleSet 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) DeleteDiffRuleSet(ctx context.Context, request diff.DeleteDiffRuleSetRequestObject) (diff.DeleteDiffRuleSetResponseObject, error) {
	return adapter.server.DeleteDiffRuleSet(ctx, request)
}

// DeleteDiffSnapshot 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) DeleteDiffSnapshot(ctx context.Context, request diff.DeleteDiffSnapshotRequestObject) (diff.DeleteDiffSnapshotResponseObject, error) {
	return adapter.server.DeleteDiffSnapshot(ctx, request)
}

// ExportDiffSnapshot 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) ExportDiffSnapshot(ctx context.Context, request diff.ExportDiffSnapshotRequestObject) (diff.ExportDiffSnapshotResponseObject, error) {
	return adapter.server.ExportDiffSnapshot(ctx, request)
}

// GetDiffSnapshot 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) GetDiffSnapshot(ctx context.Context, request diff.GetDiffSnapshotRequestObject) (diff.GetDiffSnapshotResponseObject, error) {
	return adapter.server.GetDiffSnapshot(ctx, request)
}

// ListDiffRuleSets 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) ListDiffRuleSets(ctx context.Context, request diff.ListDiffRuleSetsRequestObject) (diff.ListDiffRuleSetsResponseObject, error) {
	return adapter.server.ListDiffRuleSets(ctx, request)
}

// ListDiffSnapshots 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) ListDiffSnapshots(ctx context.Context, request diff.ListDiffSnapshotsRequestObject) (diff.ListDiffSnapshotsResponseObject, error) {
	return adapter.server.ListDiffSnapshots(ctx, request)
}

// RunDiff 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) RunDiff(ctx context.Context, request diff.RunDiffRequestObject) (diff.RunDiffResponseObject, error) {
	return adapter.server.RunDiff(ctx, request)
}

// Search 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) Search(ctx context.Context, request diff.SearchRequestObject) (diff.SearchResponseObject, error) {
	return adapter.server.Search(ctx, request)
}

// UpdateDiffRuleSet 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) UpdateDiffRuleSet(ctx context.Context, request diff.UpdateDiffRuleSetRequestObject) (diff.UpdateDiffRuleSetResponseObject, error) {
	return adapter.server.UpdateDiffRuleSet(ctx, request)
}

type jobServer struct {
	job.UnimplementedStrictServer
	server *Server
}

// CancelJob 将 job 的严格操作委托给对应的 Handler 实现。
func (adapter jobServer) CancelJob(ctx context.Context, request job.CancelJobRequestObject) (job.CancelJobResponseObject, error) {
	return adapter.server.CancelJob(ctx, request)
}

// GetJob 将 job 的严格操作委托给对应的 Handler 实现。
func (adapter jobServer) GetJob(ctx context.Context, request job.GetJobRequestObject) (job.GetJobResponseObject, error) {
	return adapter.server.GetJob(ctx, request)
}

// ListJobs 将 job 的严格操作委托给对应的 Handler 实现。
func (adapter jobServer) ListJobs(ctx context.Context, request job.ListJobsRequestObject) (job.ListJobsResponseObject, error) {
	return adapter.server.ListJobs(ctx, request)
}

// RetryJob 将 job 的严格操作委托给对应的 Handler 实现。
func (adapter jobServer) RetryJob(ctx context.Context, request job.RetryJobRequestObject) (job.RetryJobResponseObject, error) {
	return adapter.server.RetryJob(ctx, request)
}

// StreamJobLogs 将 job 的严格操作委托给对应的 Handler 实现。
func (adapter jobServer) StreamJobLogs(ctx context.Context, request job.StreamJobLogsRequestObject) (job.StreamJobLogsResponseObject, error) {
	return adapter.server.StreamJobLogs(ctx, request)
}

type layerServer struct {
	layer.UnimplementedStrictServer
	server *Server
}

// ApproveLayerRevision 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) ApproveLayerRevision(ctx context.Context, request layer.ApproveLayerRevisionRequestObject) (layer.ApproveLayerRevisionResponseObject, error) {
	return adapter.server.ApproveLayerRevision(ctx, request)
}

// CreateLayerRevision 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) CreateLayerRevision(ctx context.Context, request layer.CreateLayerRevisionRequestObject) (layer.CreateLayerRevisionResponseObject, error) {
	return adapter.server.CreateLayerRevision(ctx, request)
}

// GetLayer 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) GetLayer(ctx context.Context, request layer.GetLayerRequestObject) (layer.GetLayerResponseObject, error) {
	return adapter.server.GetLayer(ctx, request)
}

// GetLayerRevision 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) GetLayerRevision(ctx context.Context, request layer.GetLayerRevisionRequestObject) (layer.GetLayerRevisionResponseObject, error) {
	return adapter.server.GetLayerRevision(ctx, request)
}

// GetReviewContext 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) GetReviewContext(ctx context.Context, request layer.GetReviewContextRequestObject) (layer.GetReviewContextResponseObject, error) {
	return adapter.server.GetReviewContext(ctx, request)
}

// ListAssetLayerContents 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) ListAssetLayerContents(ctx context.Context, request layer.ListAssetLayerContentsRequestObject) (layer.ListAssetLayerContentsResponseObject, error) {
	return adapter.server.ListAssetLayerContents(ctx, request)
}

// ListLayerRevisions 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) ListLayerRevisions(ctx context.Context, request layer.ListLayerRevisionsRequestObject) (layer.ListLayerRevisionsResponseObject, error) {
	return adapter.server.ListLayerRevisions(ctx, request)
}

// ListReviews 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) ListReviews(ctx context.Context, request layer.ListReviewsRequestObject) (layer.ListReviewsResponseObject, error) {
	return adapter.server.ListReviews(ctx, request)
}

// RejectLayerRevision 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) RejectLayerRevision(ctx context.Context, request layer.RejectLayerRevisionRequestObject) (layer.RejectLayerRevisionResponseObject, error) {
	return adapter.server.RejectLayerRevision(ctx, request)
}

// ReorderAssetLayers 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) ReorderAssetLayers(ctx context.Context, request layer.ReorderAssetLayersRequestObject) (layer.ReorderAssetLayersResponseObject, error) {
	return adapter.server.ReorderAssetLayers(ctx, request)
}

// RollbackLayer 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) RollbackLayer(ctx context.Context, request layer.RollbackLayerRequestObject) (layer.RollbackLayerResponseObject, error) {
	return adapter.server.RollbackLayer(ctx, request)
}

// UpdateLayer 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) UpdateLayer(ctx context.Context, request layer.UpdateLayerRequestObject) (layer.UpdateLayerResponseObject, error) {
	return adapter.server.UpdateLayer(ctx, request)
}

type platformServer struct {
	platform.UnimplementedStrictServer
	server *Server
}

// CreateGlobalCredential 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) CreateGlobalCredential(ctx context.Context, request platform.CreateGlobalCredentialRequestObject) (platform.CreateGlobalCredentialResponseObject, error) {
	return adapter.server.CreateGlobalCredential(ctx, request)
}

// CreateProducerProfile 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) CreateProducerProfile(ctx context.Context, request platform.CreateProducerProfileRequestObject) (platform.CreateProducerProfileResponseObject, error) {
	return adapter.server.CreateProducerProfile(ctx, request)
}

// CreateTenant 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) CreateTenant(ctx context.Context, request platform.CreateTenantRequestObject) (platform.CreateTenantResponseObject, error) {
	return adapter.server.CreateTenant(ctx, request)
}

// CreateUser 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) CreateUser(ctx context.Context, request platform.CreateUserRequestObject) (platform.CreateUserResponseObject, error) {
	return adapter.server.CreateUser(ctx, request)
}

// DeleteGlobalCredential 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) DeleteGlobalCredential(ctx context.Context, request platform.DeleteGlobalCredentialRequestObject) (platform.DeleteGlobalCredentialResponseObject, error) {
	return adapter.server.DeleteGlobalCredential(ctx, request)
}

// DeleteProducerProfile 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) DeleteProducerProfile(ctx context.Context, request platform.DeleteProducerProfileRequestObject) (platform.DeleteProducerProfileResponseObject, error) {
	return adapter.server.DeleteProducerProfile(ctx, request)
}

// DeleteTenant 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) DeleteTenant(ctx context.Context, request platform.DeleteTenantRequestObject) (platform.DeleteTenantResponseObject, error) {
	return adapter.server.DeleteTenant(ctx, request)
}

// GetPlatformJob 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) GetPlatformJob(ctx context.Context, request platform.GetPlatformJobRequestObject) (platform.GetPlatformJobResponseObject, error) {
	return adapter.server.GetPlatformJob(ctx, request)
}

// GetPlatformSettings 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) GetPlatformSettings(ctx context.Context, request platform.GetPlatformSettingsRequestObject) (platform.GetPlatformSettingsResponseObject, error) {
	return adapter.server.GetPlatformSettings(ctx, request)
}

// GetProducerProfile 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) GetProducerProfile(ctx context.Context, request platform.GetProducerProfileRequestObject) (platform.GetProducerProfileResponseObject, error) {
	return adapter.server.GetProducerProfile(ctx, request)
}

// ListGlobalCredentials 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) ListGlobalCredentials(ctx context.Context, request platform.ListGlobalCredentialsRequestObject) (platform.ListGlobalCredentialsResponseObject, error) {
	return adapter.server.ListGlobalCredentials(ctx, request)
}

// ListPlatformAuditLogs 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) ListPlatformAuditLogs(ctx context.Context, request platform.ListPlatformAuditLogsRequestObject) (platform.ListPlatformAuditLogsResponseObject, error) {
	return adapter.server.ListPlatformAuditLogs(ctx, request)
}

// ListPlatformJobs 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) ListPlatformJobs(ctx context.Context, request platform.ListPlatformJobsRequestObject) (platform.ListPlatformJobsResponseObject, error) {
	return adapter.server.ListPlatformJobs(ctx, request)
}

// ListProducerProfiles 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) ListProducerProfiles(ctx context.Context, request platform.ListProducerProfilesRequestObject) (platform.ListProducerProfilesResponseObject, error) {
	return adapter.server.ListProducerProfiles(ctx, request)
}

// ListTenants 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) ListTenants(ctx context.Context, request platform.ListTenantsRequestObject) (platform.ListTenantsResponseObject, error) {
	return adapter.server.ListTenants(ctx, request)
}

// ListUsers 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) ListUsers(ctx context.Context, request platform.ListUsersRequestObject) (platform.ListUsersResponseObject, error) {
	return adapter.server.ListUsers(ctx, request)
}

// PutTenantMemberAsPlatformAdmin 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) PutTenantMemberAsPlatformAdmin(ctx context.Context, request platform.PutTenantMemberAsPlatformAdminRequestObject) (platform.PutTenantMemberAsPlatformAdminResponseObject, error) {
	return adapter.server.PutTenantMemberAsPlatformAdmin(ctx, request)
}

// RotateGlobalCredential 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) RotateGlobalCredential(ctx context.Context, request platform.RotateGlobalCredentialRequestObject) (platform.RotateGlobalCredentialResponseObject, error) {
	return adapter.server.RotateGlobalCredential(ctx, request)
}

// TestGlobalCredential 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) TestGlobalCredential(ctx context.Context, request platform.TestGlobalCredentialRequestObject) (platform.TestGlobalCredentialResponseObject, error) {
	return adapter.server.TestGlobalCredential(ctx, request)
}

// UpdateGlobalCredential 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) UpdateGlobalCredential(ctx context.Context, request platform.UpdateGlobalCredentialRequestObject) (platform.UpdateGlobalCredentialResponseObject, error) {
	return adapter.server.UpdateGlobalCredential(ctx, request)
}

// UpdatePlatformSettings 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) UpdatePlatformSettings(ctx context.Context, request platform.UpdatePlatformSettingsRequestObject) (platform.UpdatePlatformSettingsResponseObject, error) {
	return adapter.server.UpdatePlatformSettings(ctx, request)
}

// UpdateProducerProfile 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) UpdateProducerProfile(ctx context.Context, request platform.UpdateProducerProfileRequestObject) (platform.UpdateProducerProfileResponseObject, error) {
	return adapter.server.UpdateProducerProfile(ctx, request)
}

// UpdateTenant 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) UpdateTenant(ctx context.Context, request platform.UpdateTenantRequestObject) (platform.UpdateTenantResponseObject, error) {
	return adapter.server.UpdateTenant(ctx, request)
}

// UpdateUser 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) UpdateUser(ctx context.Context, request platform.UpdateUserRequestObject) (platform.UpdateUserResponseObject, error) {
	return adapter.server.UpdateUser(ctx, request)
}

type repositoryServer struct {
	repository.UnimplementedStrictServer
	server *Server
}

// AcceptDiscoveryCandidates 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) AcceptDiscoveryCandidates(ctx context.Context, request repository.AcceptDiscoveryCandidatesRequestObject) (repository.AcceptDiscoveryCandidatesResponseObject, error) {
	return adapter.server.AcceptDiscoveryCandidates(ctx, request)
}

// ApplyRepositoryConfigImport 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) ApplyRepositoryConfigImport(ctx context.Context, request repository.ApplyRepositoryConfigImportRequestObject) (repository.ApplyRepositoryConfigImportResponseObject, error) {
	return adapter.server.ApplyRepositoryConfigImport(ctx, request)
}

// CheckRepositoryConnection 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) CheckRepositoryConnection(ctx context.Context, request repository.CheckRepositoryConnectionRequestObject) (repository.CheckRepositoryConnectionResponseObject, error) {
	return adapter.server.CheckRepositoryConnection(ctx, request)
}

// CreateRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) CreateRepository(ctx context.Context, request repository.CreateRepositoryRequestObject) (repository.CreateRepositoryResponseObject, error) {
	return adapter.server.CreateRepository(ctx, request)
}

// DeleteRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) DeleteRepository(ctx context.Context, request repository.DeleteRepositoryRequestObject) (repository.DeleteRepositoryResponseObject, error) {
	return adapter.server.DeleteRepository(ctx, request)
}

// DiscoverRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) DiscoverRepository(ctx context.Context, request repository.DiscoverRepositoryRequestObject) (repository.DiscoverRepositoryResponseObject, error) {
	return adapter.server.DiscoverRepository(ctx, request)
}

// DismissDiscoveryCandidate 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) DismissDiscoveryCandidate(ctx context.Context, request repository.DismissDiscoveryCandidateRequestObject) (repository.DismissDiscoveryCandidateResponseObject, error) {
	return adapter.server.DismissDiscoveryCandidate(ctx, request)
}

// GetRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) GetRepository(ctx context.Context, request repository.GetRepositoryRequestObject) (repository.GetRepositoryResponseObject, error) {
	return adapter.server.GetRepository(ctx, request)
}

// ListDiscoveryCandidates 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) ListDiscoveryCandidates(ctx context.Context, request repository.ListDiscoveryCandidatesRequestObject) (repository.ListDiscoveryCandidatesResponseObject, error) {
	return adapter.server.ListDiscoveryCandidates(ctx, request)
}

// ListRepositories 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) ListRepositories(ctx context.Context, request repository.ListRepositoriesRequestObject) (repository.ListRepositoriesResponseObject, error) {
	return adapter.server.ListRepositories(ctx, request)
}

// PreviewRepositoryConfigImport 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) PreviewRepositoryConfigImport(ctx context.Context, request repository.PreviewRepositoryConfigImportRequestObject) (repository.PreviewRepositoryConfigImportResponseObject, error) {
	return adapter.server.PreviewRepositoryConfigImport(ctx, request)
}

// ReceiveGitWebhook 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) ReceiveGitWebhook(ctx context.Context, request repository.ReceiveGitWebhookRequestObject) (repository.ReceiveGitWebhookResponseObject, error) {
	return adapter.server.ReceiveGitWebhook(ctx, request)
}

// SyncRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) SyncRepository(ctx context.Context, request repository.SyncRepositoryRequestObject) (repository.SyncRepositoryResponseObject, error) {
	return adapter.server.SyncRepository(ctx, request)
}

// UpdateRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) UpdateRepository(ctx context.Context, request repository.UpdateRepositoryRequestObject) (repository.UpdateRepositoryResponseObject, error) {
	return adapter.server.UpdateRepository(ctx, request)
}

type serviceServer struct {
	serviceapi.UnimplementedStrictServer
	server *Server
}

// CreateServiceInRepository 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) CreateServiceInRepository(ctx context.Context, request serviceapi.CreateServiceInRepositoryRequestObject) (serviceapi.CreateServiceInRepositoryResponseObject, error) {
	return adapter.server.CreateServiceInRepository(ctx, request)
}

// DeleteService 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) DeleteService(ctx context.Context, request serviceapi.DeleteServiceRequestObject) (serviceapi.DeleteServiceResponseObject, error) {
	return adapter.server.DeleteService(ctx, request)
}

// GetPublicService 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) GetPublicService(ctx context.Context, request serviceapi.GetPublicServiceRequestObject) (serviceapi.GetPublicServiceResponseObject, error) {
	return adapter.server.GetPublicService(ctx, request)
}

// GetService 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) GetService(ctx context.Context, request serviceapi.GetServiceRequestObject) (serviceapi.GetServiceResponseObject, error) {
	return adapter.server.GetService(ctx, request)
}

// ListRecentServices 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) ListRecentServices(ctx context.Context, request serviceapi.ListRecentServicesRequestObject) (serviceapi.ListRecentServicesResponseObject, error) {
	return adapter.server.ListRecentServices(ctx, request)
}

// ListServices 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) ListServices(ctx context.Context, request serviceapi.ListServicesRequestObject) (serviceapi.ListServicesResponseObject, error) {
	return adapter.server.ListServices(ctx, request)
}

// StarService 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) StarService(ctx context.Context, request serviceapi.StarServiceRequestObject) (serviceapi.StarServiceResponseObject, error) {
	return adapter.server.StarService(ctx, request)
}

// UnstarService 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) UnstarService(ctx context.Context, request serviceapi.UnstarServiceRequestObject) (serviceapi.UnstarServiceResponseObject, error) {
	return adapter.server.UnstarService(ctx, request)
}

// UpdateService 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) UpdateService(ctx context.Context, request serviceapi.UpdateServiceRequestObject) (serviceapi.UpdateServiceResponseObject, error) {
	return adapter.server.UpdateService(ctx, request)
}

type systemServer struct {
	system.UnimplementedStrictServer
	server *Server
}

// DownloadSignedContent 将 system 的严格操作委托给对应的 Handler 实现。
func (adapter systemServer) DownloadSignedContent(ctx context.Context, request system.DownloadSignedContentRequestObject) (system.DownloadSignedContentResponseObject, error) {
	return adapter.server.DownloadSignedContent(ctx, request)
}

// GetOpenApiContract 将 system 的严格操作委托给对应的 Handler 实现。
func (adapter systemServer) GetOpenApiContract(ctx context.Context, request system.GetOpenApiContractRequestObject) (system.GetOpenApiContractResponseObject, error) {
	return adapter.server.GetOpenApiContract(ctx, request)
}

// GetVersion 将 system 的严格操作委托给对应的 Handler 实现。
func (adapter systemServer) GetVersion(ctx context.Context, request system.GetVersionRequestObject) (system.GetVersionResponseObject, error) {
	return adapter.server.GetVersion(ctx, request)
}

// Healthz 将 system 的严格操作委托给对应的 Handler 实现。
func (adapter systemServer) Healthz(ctx context.Context, request system.HealthzRequestObject) (system.HealthzResponseObject, error) {
	return adapter.server.Healthz(ctx, request)
}

// Metrics 将 system 的严格操作委托给对应的 Handler 实现。
func (adapter systemServer) Metrics(ctx context.Context, request system.MetricsRequestObject) (system.MetricsResponseObject, error) {
	return adapter.server.Metrics(ctx, request)
}

// Readyz 将 system 的严格操作委托给对应的 Handler 实现。
func (adapter systemServer) Readyz(ctx context.Context, request system.ReadyzRequestObject) (system.ReadyzResponseObject, error) {
	return adapter.server.Readyz(ctx, request)
}

type tenantServer struct {
	tenant.UnimplementedStrictServer
	server *Server
}

// CreateCredential 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) CreateCredential(ctx context.Context, request tenant.CreateCredentialRequestObject) (tenant.CreateCredentialResponseObject, error) {
	return adapter.server.CreateCredential(ctx, request)
}

// CreateKnownHost 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) CreateKnownHost(ctx context.Context, request tenant.CreateKnownHostRequestObject) (tenant.CreateKnownHostResponseObject, error) {
	return adapter.server.CreateKnownHost(ctx, request)
}

// CreateTag 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) CreateTag(ctx context.Context, request tenant.CreateTagRequestObject) (tenant.CreateTagResponseObject, error) {
	return adapter.server.CreateTag(ctx, request)
}

// CreateTeam 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) CreateTeam(ctx context.Context, request tenant.CreateTeamRequestObject) (tenant.CreateTeamResponseObject, error) {
	return adapter.server.CreateTeam(ctx, request)
}

// CreateTenantExport 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) CreateTenantExport(ctx context.Context, request tenant.CreateTenantExportRequestObject) (tenant.CreateTenantExportResponseObject, error) {
	return adapter.server.CreateTenantExport(ctx, request)
}

// CreateToken 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) CreateToken(ctx context.Context, request tenant.CreateTokenRequestObject) (tenant.CreateTokenResponseObject, error) {
	return adapter.server.CreateToken(ctx, request)
}

// DeleteCredential 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) DeleteCredential(ctx context.Context, request tenant.DeleteCredentialRequestObject) (tenant.DeleteCredentialResponseObject, error) {
	return adapter.server.DeleteCredential(ctx, request)
}

// DeleteTag 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) DeleteTag(ctx context.Context, request tenant.DeleteTagRequestObject) (tenant.DeleteTagResponseObject, error) {
	return adapter.server.DeleteTag(ctx, request)
}

// DeleteTeam 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) DeleteTeam(ctx context.Context, request tenant.DeleteTeamRequestObject) (tenant.DeleteTeamResponseObject, error) {
	return adapter.server.DeleteTeam(ctx, request)
}

// DeleteTenantMember 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) DeleteTenantMember(ctx context.Context, request tenant.DeleteTenantMemberRequestObject) (tenant.DeleteTenantMemberResponseObject, error) {
	return adapter.server.DeleteTenantMember(ctx, request)
}

// GetTeam 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) GetTeam(ctx context.Context, request tenant.GetTeamRequestObject) (tenant.GetTeamResponseObject, error) {
	return adapter.server.GetTeam(ctx, request)
}

// GetTenantSettings 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) GetTenantSettings(ctx context.Context, request tenant.GetTenantSettingsRequestObject) (tenant.GetTenantSettingsResponseObject, error) {
	return adapter.server.GetTenantSettings(ctx, request)
}

// ListAvailableProducerProfiles 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ListAvailableProducerProfiles(ctx context.Context, request tenant.ListAvailableProducerProfilesRequestObject) (tenant.ListAvailableProducerProfilesResponseObject, error) {
	return adapter.server.ListAvailableProducerProfiles(ctx, request)
}

// ListCredentials 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ListCredentials(ctx context.Context, request tenant.ListCredentialsRequestObject) (tenant.ListCredentialsResponseObject, error) {
	return adapter.server.ListCredentials(ctx, request)
}

// ListKnownHosts 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ListKnownHosts(ctx context.Context, request tenant.ListKnownHostsRequestObject) (tenant.ListKnownHostsResponseObject, error) {
	return adapter.server.ListKnownHosts(ctx, request)
}

// ListTags 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ListTags(ctx context.Context, request tenant.ListTagsRequestObject) (tenant.ListTagsResponseObject, error) {
	return adapter.server.ListTags(ctx, request)
}

// ListTeams 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ListTeams(ctx context.Context, request tenant.ListTeamsRequestObject) (tenant.ListTeamsResponseObject, error) {
	return adapter.server.ListTeams(ctx, request)
}

// ListTenantMembers 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ListTenantMembers(ctx context.Context, request tenant.ListTenantMembersRequestObject) (tenant.ListTenantMembersResponseObject, error) {
	return adapter.server.ListTenantMembers(ctx, request)
}

// ListTokens 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ListTokens(ctx context.Context, request tenant.ListTokensRequestObject) (tenant.ListTokensResponseObject, error) {
	return adapter.server.ListTokens(ctx, request)
}

// PutTenantMember 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) PutTenantMember(ctx context.Context, request tenant.PutTenantMemberRequestObject) (tenant.PutTenantMemberResponseObject, error) {
	return adapter.server.PutTenantMember(ctx, request)
}

// ReplaceTeamMembers 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ReplaceTeamMembers(ctx context.Context, request tenant.ReplaceTeamMembersRequestObject) (tenant.ReplaceTeamMembersResponseObject, error) {
	return adapter.server.ReplaceTeamMembers(ctx, request)
}

// RevokeToken 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) RevokeToken(ctx context.Context, request tenant.RevokeTokenRequestObject) (tenant.RevokeTokenResponseObject, error) {
	return adapter.server.RevokeToken(ctx, request)
}

// RotateCredential 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) RotateCredential(ctx context.Context, request tenant.RotateCredentialRequestObject) (tenant.RotateCredentialResponseObject, error) {
	return adapter.server.RotateCredential(ctx, request)
}

// SearchTenantUsers 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) SearchTenantUsers(ctx context.Context, request tenant.SearchTenantUsersRequestObject) (tenant.SearchTenantUsersResponseObject, error) {
	return adapter.server.SearchTenantUsers(ctx, request)
}

// TestCredential 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) TestCredential(ctx context.Context, request tenant.TestCredentialRequestObject) (tenant.TestCredentialResponseObject, error) {
	return adapter.server.TestCredential(ctx, request)
}

// UpdateCredential 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) UpdateCredential(ctx context.Context, request tenant.UpdateCredentialRequestObject) (tenant.UpdateCredentialResponseObject, error) {
	return adapter.server.UpdateCredential(ctx, request)
}

// UpdateTag 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) UpdateTag(ctx context.Context, request tenant.UpdateTagRequestObject) (tenant.UpdateTagResponseObject, error) {
	return adapter.server.UpdateTag(ctx, request)
}

// UpdateTeam 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) UpdateTeam(ctx context.Context, request tenant.UpdateTeamRequestObject) (tenant.UpdateTeamResponseObject, error) {
	return adapter.server.UpdateTeam(ctx, request)
}

// UpdateTenantSettings 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) UpdateTenantSettings(ctx context.Context, request tenant.UpdateTenantSettingsRequestObject) (tenant.UpdateTenantSettingsResponseObject, error) {
	return adapter.server.UpdateTenantSettings(ctx, request)
}

type viewServer struct {
	view.UnimplementedStrictServer
	server *Server
}

// CreateShareLink 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) CreateShareLink(ctx context.Context, request view.CreateShareLinkRequestObject) (view.CreateShareLinkResponseObject, error) {
	return adapter.server.CreateShareLink(ctx, request)
}

// CreateSystemGroup 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) CreateSystemGroup(ctx context.Context, request view.CreateSystemGroupRequestObject) (view.CreateSystemGroupResponseObject, error) {
	return adapter.server.CreateSystemGroup(ctx, request)
}

// DeleteSystemGroup 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) DeleteSystemGroup(ctx context.Context, request view.DeleteSystemGroupRequestObject) (view.DeleteSystemGroupResponseObject, error) {
	return adapter.server.DeleteSystemGroup(ctx, request)
}

// DeleteViewOverride 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) DeleteViewOverride(ctx context.Context, request view.DeleteViewOverrideRequestObject) (view.DeleteViewOverrideResponseObject, error) {
	return adapter.server.DeleteViewOverride(ctx, request)
}

// GetSharedView 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) GetSharedView(ctx context.Context, request view.GetSharedViewRequestObject) (view.GetSharedViewResponseObject, error) {
	return adapter.server.GetSharedView(ctx, request)
}

// GetSystemGroup 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) GetSystemGroup(ctx context.Context, request view.GetSystemGroupRequestObject) (view.GetSystemGroupResponseObject, error) {
	return adapter.server.GetSystemGroup(ctx, request)
}

// ListShareLinks 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) ListShareLinks(ctx context.Context, request view.ListShareLinksRequestObject) (view.ListShareLinksResponseObject, error) {
	return adapter.server.ListShareLinks(ctx, request)
}

// ListSystemGroups 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) ListSystemGroups(ctx context.Context, request view.ListSystemGroupsRequestObject) (view.ListSystemGroupsResponseObject, error) {
	return adapter.server.ListSystemGroups(ctx, request)
}

// ListViewOverrides 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) ListViewOverrides(ctx context.Context, request view.ListViewOverridesRequestObject) (view.ListViewOverridesResponseObject, error) {
	return adapter.server.ListViewOverrides(ctx, request)
}

// ListViews 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) ListViews(ctx context.Context, request view.ListViewsRequestObject) (view.ListViewsResponseObject, error) {
	return adapter.server.ListViews(ctx, request)
}

// PreviewAssetView 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) PreviewAssetView(ctx context.Context, request view.PreviewAssetViewRequestObject) (view.PreviewAssetViewResponseObject, error) {
	return adapter.server.PreviewAssetView(ctx, request)
}

// PutSystemGroupMembers 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) PutSystemGroupMembers(ctx context.Context, request view.PutSystemGroupMembersRequestObject) (view.PutSystemGroupMembersResponseObject, error) {
	return adapter.server.PutSystemGroupMembers(ctx, request)
}

// PutViewOverride 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) PutViewOverride(ctx context.Context, request view.PutViewOverrideRequestObject) (view.PutViewOverrideResponseObject, error) {
	return adapter.server.PutViewOverride(ctx, request)
}

// ResolvePublicView 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) ResolvePublicView(ctx context.Context, request view.ResolvePublicViewRequestObject) (view.ResolvePublicViewResponseObject, error) {
	return adapter.server.ResolvePublicView(ctx, request)
}

// ResolveView 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) ResolveView(ctx context.Context, request view.ResolveViewRequestObject) (view.ResolveViewResponseObject, error) {
	return adapter.server.ResolveView(ctx, request)
}

// RevokeShareLink 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) RevokeShareLink(ctx context.Context, request view.RevokeShareLinkRequestObject) (view.RevokeShareLinkResponseObject, error) {
	return adapter.server.RevokeShareLink(ctx, request)
}

// UpdateSystemGroup 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) UpdateSystemGroup(ctx context.Context, request view.UpdateSystemGroupRequestObject) (view.UpdateSystemGroupResponseObject, error) {
	return adapter.server.UpdateSystemGroup(ctx, request)
}

func registerDomainHandlers(server *Server, router chi.Router) {
	assetStrict := asset.NewStrictHandlerWithOptions(assetServer{server: server}, []asset.StrictMiddlewareFunc{
		func(next asset.StrictHandlerFunc, operationID string) asset.StrictHandlerFunc {
			return asset.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, asset.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	asset.HandlerFromMux(assetStrict, router)
	authStrict := auth.NewStrictHandlerWithOptions(authServer{server: server}, []auth.StrictMiddlewareFunc{
		func(next auth.StrictHandlerFunc, operationID string) auth.StrictHandlerFunc {
			return auth.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, auth.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	auth.HandlerFromMux(authStrict, router)
	collaborationStrict := collaboration.NewStrictHandlerWithOptions(collaborationServer{server: server}, []collaboration.StrictMiddlewareFunc{
		func(next collaboration.StrictHandlerFunc, operationID string) collaboration.StrictHandlerFunc {
			return collaboration.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, collaboration.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	collaboration.HandlerFromMux(collaborationStrict, router)
	diffStrict := diff.NewStrictHandlerWithOptions(diffServer{server: server}, []diff.StrictMiddlewareFunc{
		func(next diff.StrictHandlerFunc, operationID string) diff.StrictHandlerFunc {
			return diff.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, diff.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	diff.HandlerFromMux(diffStrict, router)
	jobStrict := job.NewStrictHandlerWithOptions(jobServer{server: server}, []job.StrictMiddlewareFunc{
		func(next job.StrictHandlerFunc, operationID string) job.StrictHandlerFunc {
			return job.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, job.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	job.HandlerFromMux(jobStrict, router)
	layerStrict := layer.NewStrictHandlerWithOptions(layerServer{server: server}, []layer.StrictMiddlewareFunc{
		func(next layer.StrictHandlerFunc, operationID string) layer.StrictHandlerFunc {
			return layer.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, layer.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	layer.HandlerFromMux(layerStrict, router)
	platformStrict := platform.NewStrictHandlerWithOptions(platformServer{server: server}, []platform.StrictMiddlewareFunc{
		func(next platform.StrictHandlerFunc, operationID string) platform.StrictHandlerFunc {
			return platform.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, platform.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	platform.HandlerFromMux(platformStrict, router)
	repositoryStrict := repository.NewStrictHandlerWithOptions(repositoryServer{server: server}, []repository.StrictMiddlewareFunc{
		func(next repository.StrictHandlerFunc, operationID string) repository.StrictHandlerFunc {
			return repository.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, repository.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	repository.HandlerFromMux(repositoryStrict, router)
	serviceStrict := serviceapi.NewStrictHandlerWithOptions(serviceServer{server: server}, []serviceapi.StrictMiddlewareFunc{
		func(next serviceapi.StrictHandlerFunc, operationID string) serviceapi.StrictHandlerFunc {
			return serviceapi.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, serviceapi.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	serviceapi.HandlerFromMux(serviceStrict, router)
	systemStrict := system.NewStrictHandlerWithOptions(systemServer{server: server}, []system.StrictMiddlewareFunc{
		func(next system.StrictHandlerFunc, operationID string) system.StrictHandlerFunc {
			return system.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, system.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	system.HandlerFromMux(systemStrict, router)
	tenantStrict := tenant.NewStrictHandlerWithOptions(tenantServer{server: server}, []tenant.StrictMiddlewareFunc{
		func(next tenant.StrictHandlerFunc, operationID string) tenant.StrictHandlerFunc {
			return tenant.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, tenant.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	tenant.HandlerFromMux(tenantStrict, router)
	viewStrict := view.NewStrictHandlerWithOptions(viewServer{server: server}, []view.StrictMiddlewareFunc{
		func(next view.StrictHandlerFunc, operationID string) view.StrictHandlerFunc {
			return view.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, view.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	view.HandlerFromMux(viewStrict, router)
}
