// Code generated by internal/codegen/domainadapter. DO NOT EDIT.

package handler

import (
	"context"

	"github.com/go-chi/chi/v5"
	"github.com/meridian-labs/meridian/internal/generated/api/asset"
	"github.com/meridian-labs/meridian/internal/generated/api/auth"
	"github.com/meridian-labs/meridian/internal/generated/api/collaboration"
	"github.com/meridian-labs/meridian/internal/generated/api/diff"
	"github.com/meridian-labs/meridian/internal/generated/api/job"
	"github.com/meridian-labs/meridian/internal/generated/api/layer"
	"github.com/meridian-labs/meridian/internal/generated/api/platform"
	"github.com/meridian-labs/meridian/internal/generated/api/repository"
	serviceapi "github.com/meridian-labs/meridian/internal/generated/api/service"
	"github.com/meridian-labs/meridian/internal/generated/api/system"
	"github.com/meridian-labs/meridian/internal/generated/api/tenant"
	"github.com/meridian-labs/meridian/internal/generated/api/view"
)

type assetServer struct {
	asset.UnimplementedStrictServer
	server *Server
}

// CreateSourceSpec 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) CreateSourceSpec(ctx context.Context, request asset.CreateSourceSpecRequestObject) (asset.CreateSourceSpecResponseObject, error) {
	return adapter.server.CreateSourceSpec(ctx, request)
}

// GenerateMissingAssetWithAi 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) GenerateMissingAssetWithAi(ctx context.Context, request asset.GenerateMissingAssetWithAiRequestObject) (asset.GenerateMissingAssetWithAiResponseObject, error) {
	return adapter.server.GenerateMissingAssetWithAi(ctx, request)
}

// GetAsset 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) GetAsset(ctx context.Context, request asset.GetAssetRequestObject) (asset.GetAssetResponseObject, error) {
	return adapter.server.GetAsset(ctx, request)
}

// GetAssetVersion 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) GetAssetVersion(ctx context.Context, request asset.GetAssetVersionRequestObject) (asset.GetAssetVersionResponseObject, error) {
	return adapter.server.GetAssetVersion(ctx, request)
}

// GetAssetVersionProvenance 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) GetAssetVersionProvenance(ctx context.Context, request asset.GetAssetVersionProvenanceRequestObject) (asset.GetAssetVersionProvenanceResponseObject, error) {
	return adapter.server.GetAssetVersionProvenance(ctx, request)
}

// ListAssetVersionItems 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) ListAssetVersionItems(ctx context.Context, request asset.ListAssetVersionItemsRequestObject) (asset.ListAssetVersionItemsResponseObject, error) {
	return adapter.server.ListAssetVersionItems(ctx, request)
}

// ListSourceBindings 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) ListSourceBindings(ctx context.Context, request asset.ListSourceBindingsRequestObject) (asset.ListSourceBindingsResponseObject, error) {
	return adapter.server.ListSourceBindings(ctx, request)
}

// ListSourceSpecs 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) ListSourceSpecs(ctx context.Context, request asset.ListSourceSpecsRequestObject) (asset.ListSourceSpecsResponseObject, error) {
	return adapter.server.ListSourceSpecs(ctx, request)
}

// PreviewMerge 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) PreviewMerge(ctx context.Context, request asset.PreviewMergeRequestObject) (asset.PreviewMergeResponseObject, error) {
	return adapter.server.PreviewMerge(ctx, request)
}

// PublishAssetVersion 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) PublishAssetVersion(ctx context.Context, request asset.PublishAssetVersionRequestObject) (asset.PublishAssetVersionResponseObject, error) {
	return adapter.server.PublishAssetVersion(ctx, request)
}

// PushAssetRevision 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) PushAssetRevision(ctx context.Context, request asset.PushAssetRevisionRequestObject) (asset.PushAssetRevisionResponseObject, error) {
	return adapter.server.PushAssetRevision(ctx, request)
}

// UpdateSourceSpec 将 asset 的严格操作委托给对应的 Handler 实现。
func (adapter assetServer) UpdateSourceSpec(ctx context.Context, request asset.UpdateSourceSpecRequestObject) (asset.UpdateSourceSpecResponseObject, error) {
	return adapter.server.UpdateSourceSpec(ctx, request)
}

type authServer struct {
	auth.UnimplementedStrictServer
	server *Server
}

// GetMe 将 auth 的严格操作委托给对应的 Handler 实现。
func (adapter authServer) GetMe(ctx context.Context, request auth.GetMeRequestObject) (auth.GetMeResponseObject, error) {
	return adapter.server.GetMe(ctx, request)
}

// Login 将 auth 的严格操作委托给对应的 Handler 实现。
func (adapter authServer) Login(ctx context.Context, request auth.LoginRequestObject) (auth.LoginResponseObject, error) {
	return adapter.server.Login(ctx, request)
}

// Logout 将 auth 的严格操作委托给对应的 Handler 实现。
func (adapter authServer) Logout(ctx context.Context, request auth.LogoutRequestObject) (auth.LogoutResponseObject, error) {
	return adapter.server.Logout(ctx, request)
}

// Refresh 将 auth 的严格操作委托给对应的 Handler 实现。
func (adapter authServer) Refresh(ctx context.Context, request auth.RefreshRequestObject) (auth.RefreshResponseObject, error) {
	return adapter.server.Refresh(ctx, request)
}

type collaborationServer struct {
	collaboration.UnimplementedStrictServer
	server *Server
}

// AcknowledgeBreakingTodo 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) AcknowledgeBreakingTodo(ctx context.Context, request collaboration.AcknowledgeBreakingTodoRequestObject) (collaboration.AcknowledgeBreakingTodoResponseObject, error) {
	return adapter.server.AcknowledgeBreakingTodo(ctx, request)
}

// ListAuditLogs 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) ListAuditLogs(ctx context.Context, request collaboration.ListAuditLogsRequestObject) (collaboration.ListAuditLogsResponseObject, error) {
	return adapter.server.ListAuditLogs(ctx, request)
}

// ListBreakingTodos 将 collaboration 的严格操作委托给对应的 Handler 实现。
func (adapter collaborationServer) ListBreakingTodos(ctx context.Context, request collaboration.ListBreakingTodosRequestObject) (collaboration.ListBreakingTodosResponseObject, error) {
	return adapter.server.ListBreakingTodos(ctx, request)
}

type diffServer struct {
	diff.UnimplementedStrictServer
	server *Server
}

// CreateDiffSnapshotShareLink 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) CreateDiffSnapshotShareLink(ctx context.Context, request diff.CreateDiffSnapshotShareLinkRequestObject) (diff.CreateDiffSnapshotShareLinkResponseObject, error) {
	return adapter.server.CreateDiffSnapshotShareLink(ctx, request)
}

// RunDiff 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) RunDiff(ctx context.Context, request diff.RunDiffRequestObject) (diff.RunDiffResponseObject, error) {
	return adapter.server.RunDiff(ctx, request)
}

// Search 将 diff 的严格操作委托给对应的 Handler 实现。
func (adapter diffServer) Search(ctx context.Context, request diff.SearchRequestObject) (diff.SearchResponseObject, error) {
	return adapter.server.Search(ctx, request)
}

type jobServer struct {
	job.UnimplementedStrictServer
	server *Server
}

// CancelJob 将 job 的严格操作委托给对应的 Handler 实现。
func (adapter jobServer) CancelJob(ctx context.Context, request job.CancelJobRequestObject) (job.CancelJobResponseObject, error) {
	return adapter.server.CancelJob(ctx, request)
}

// GetJob 将 job 的严格操作委托给对应的 Handler 实现。
func (adapter jobServer) GetJob(ctx context.Context, request job.GetJobRequestObject) (job.GetJobResponseObject, error) {
	return adapter.server.GetJob(ctx, request)
}

// ListJobs 将 job 的严格操作委托给对应的 Handler 实现。
func (adapter jobServer) ListJobs(ctx context.Context, request job.ListJobsRequestObject) (job.ListJobsResponseObject, error) {
	return adapter.server.ListJobs(ctx, request)
}

// RetryJob 将 job 的严格操作委托给对应的 Handler 实现。
func (adapter jobServer) RetryJob(ctx context.Context, request job.RetryJobRequestObject) (job.RetryJobResponseObject, error) {
	return adapter.server.RetryJob(ctx, request)
}

// StreamJobLogs 将 job 的严格操作委托给对应的 Handler 实现。
func (adapter jobServer) StreamJobLogs(ctx context.Context, request job.StreamJobLogsRequestObject) (job.StreamJobLogsResponseObject, error) {
	return adapter.server.StreamJobLogs(ctx, request)
}

type layerServer struct {
	layer.UnimplementedStrictServer
	server *Server
}

// ApproveLayerRevision 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) ApproveLayerRevision(ctx context.Context, request layer.ApproveLayerRevisionRequestObject) (layer.ApproveLayerRevisionResponseObject, error) {
	return adapter.server.ApproveLayerRevision(ctx, request)
}

// CreateLayerRevision 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) CreateLayerRevision(ctx context.Context, request layer.CreateLayerRevisionRequestObject) (layer.CreateLayerRevisionResponseObject, error) {
	return adapter.server.CreateLayerRevision(ctx, request)
}

// GetReviewContext 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) GetReviewContext(ctx context.Context, request layer.GetReviewContextRequestObject) (layer.GetReviewContextResponseObject, error) {
	return adapter.server.GetReviewContext(ctx, request)
}

// RejectLayerRevision 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) RejectLayerRevision(ctx context.Context, request layer.RejectLayerRevisionRequestObject) (layer.RejectLayerRevisionResponseObject, error) {
	return adapter.server.RejectLayerRevision(ctx, request)
}

// ReorderAssetLayers 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) ReorderAssetLayers(ctx context.Context, request layer.ReorderAssetLayersRequestObject) (layer.ReorderAssetLayersResponseObject, error) {
	return adapter.server.ReorderAssetLayers(ctx, request)
}

// RollbackLayer 将 layer 的严格操作委托给对应的 Handler 实现。
func (adapter layerServer) RollbackLayer(ctx context.Context, request layer.RollbackLayerRequestObject) (layer.RollbackLayerResponseObject, error) {
	return adapter.server.RollbackLayer(ctx, request)
}

type platformServer struct {
	platform.UnimplementedStrictServer
	server *Server
}

// CreateGlobalCredential 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) CreateGlobalCredential(ctx context.Context, request platform.CreateGlobalCredentialRequestObject) (platform.CreateGlobalCredentialResponseObject, error) {
	return adapter.server.CreateGlobalCredential(ctx, request)
}

// CreateProducerProfile 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) CreateProducerProfile(ctx context.Context, request platform.CreateProducerProfileRequestObject) (platform.CreateProducerProfileResponseObject, error) {
	return adapter.server.CreateProducerProfile(ctx, request)
}

// CreateTenant 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) CreateTenant(ctx context.Context, request platform.CreateTenantRequestObject) (platform.CreateTenantResponseObject, error) {
	return adapter.server.CreateTenant(ctx, request)
}

// CreateUser 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) CreateUser(ctx context.Context, request platform.CreateUserRequestObject) (platform.CreateUserResponseObject, error) {
	return adapter.server.CreateUser(ctx, request)
}

// DeleteGlobalCredential 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) DeleteGlobalCredential(ctx context.Context, request platform.DeleteGlobalCredentialRequestObject) (platform.DeleteGlobalCredentialResponseObject, error) {
	return adapter.server.DeleteGlobalCredential(ctx, request)
}

// GetPlatformJob 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) GetPlatformJob(ctx context.Context, request platform.GetPlatformJobRequestObject) (platform.GetPlatformJobResponseObject, error) {
	return adapter.server.GetPlatformJob(ctx, request)
}

// ListGlobalCredentials 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) ListGlobalCredentials(ctx context.Context, request platform.ListGlobalCredentialsRequestObject) (platform.ListGlobalCredentialsResponseObject, error) {
	return adapter.server.ListGlobalCredentials(ctx, request)
}

// ListPlatformAuditLogs 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) ListPlatformAuditLogs(ctx context.Context, request platform.ListPlatformAuditLogsRequestObject) (platform.ListPlatformAuditLogsResponseObject, error) {
	return adapter.server.ListPlatformAuditLogs(ctx, request)
}

// ListPlatformJobs 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) ListPlatformJobs(ctx context.Context, request platform.ListPlatformJobsRequestObject) (platform.ListPlatformJobsResponseObject, error) {
	return adapter.server.ListPlatformJobs(ctx, request)
}

// ListTenants 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) ListTenants(ctx context.Context, request platform.ListTenantsRequestObject) (platform.ListTenantsResponseObject, error) {
	return adapter.server.ListTenants(ctx, request)
}

// ListUsers 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) ListUsers(ctx context.Context, request platform.ListUsersRequestObject) (platform.ListUsersResponseObject, error) {
	return adapter.server.ListUsers(ctx, request)
}

// PutTenantMemberAsPlatformAdmin 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) PutTenantMemberAsPlatformAdmin(ctx context.Context, request platform.PutTenantMemberAsPlatformAdminRequestObject) (platform.PutTenantMemberAsPlatformAdminResponseObject, error) {
	return adapter.server.PutTenantMemberAsPlatformAdmin(ctx, request)
}

// RotateGlobalCredential 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) RotateGlobalCredential(ctx context.Context, request platform.RotateGlobalCredentialRequestObject) (platform.RotateGlobalCredentialResponseObject, error) {
	return adapter.server.RotateGlobalCredential(ctx, request)
}

// TestGlobalCredential 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) TestGlobalCredential(ctx context.Context, request platform.TestGlobalCredentialRequestObject) (platform.TestGlobalCredentialResponseObject, error) {
	return adapter.server.TestGlobalCredential(ctx, request)
}

// UpdateGlobalCredential 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) UpdateGlobalCredential(ctx context.Context, request platform.UpdateGlobalCredentialRequestObject) (platform.UpdateGlobalCredentialResponseObject, error) {
	return adapter.server.UpdateGlobalCredential(ctx, request)
}

// UpdateTenant 将 platform 的严格操作委托给对应的 Handler 实现。
func (adapter platformServer) UpdateTenant(ctx context.Context, request platform.UpdateTenantRequestObject) (platform.UpdateTenantResponseObject, error) {
	return adapter.server.UpdateTenant(ctx, request)
}

type repositoryServer struct {
	repository.UnimplementedStrictServer
	server *Server
}

// AcceptDiscoveryCandidates 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) AcceptDiscoveryCandidates(ctx context.Context, request repository.AcceptDiscoveryCandidatesRequestObject) (repository.AcceptDiscoveryCandidatesResponseObject, error) {
	return adapter.server.AcceptDiscoveryCandidates(ctx, request)
}

// ApplyRepositoryConfigImport 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) ApplyRepositoryConfigImport(ctx context.Context, request repository.ApplyRepositoryConfigImportRequestObject) (repository.ApplyRepositoryConfigImportResponseObject, error) {
	return adapter.server.ApplyRepositoryConfigImport(ctx, request)
}

// CheckRepositoryConnection 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) CheckRepositoryConnection(ctx context.Context, request repository.CheckRepositoryConnectionRequestObject) (repository.CheckRepositoryConnectionResponseObject, error) {
	return adapter.server.CheckRepositoryConnection(ctx, request)
}

// CreateRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) CreateRepository(ctx context.Context, request repository.CreateRepositoryRequestObject) (repository.CreateRepositoryResponseObject, error) {
	return adapter.server.CreateRepository(ctx, request)
}

// DeleteRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) DeleteRepository(ctx context.Context, request repository.DeleteRepositoryRequestObject) (repository.DeleteRepositoryResponseObject, error) {
	return adapter.server.DeleteRepository(ctx, request)
}

// DiscoverRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) DiscoverRepository(ctx context.Context, request repository.DiscoverRepositoryRequestObject) (repository.DiscoverRepositoryResponseObject, error) {
	return adapter.server.DiscoverRepository(ctx, request)
}

// GetRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) GetRepository(ctx context.Context, request repository.GetRepositoryRequestObject) (repository.GetRepositoryResponseObject, error) {
	return adapter.server.GetRepository(ctx, request)
}

// ListDiscoveryCandidates 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) ListDiscoveryCandidates(ctx context.Context, request repository.ListDiscoveryCandidatesRequestObject) (repository.ListDiscoveryCandidatesResponseObject, error) {
	return adapter.server.ListDiscoveryCandidates(ctx, request)
}

// ListRepositories 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) ListRepositories(ctx context.Context, request repository.ListRepositoriesRequestObject) (repository.ListRepositoriesResponseObject, error) {
	return adapter.server.ListRepositories(ctx, request)
}

// PreviewRepositoryConfigImport 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) PreviewRepositoryConfigImport(ctx context.Context, request repository.PreviewRepositoryConfigImportRequestObject) (repository.PreviewRepositoryConfigImportResponseObject, error) {
	return adapter.server.PreviewRepositoryConfigImport(ctx, request)
}

// SyncRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) SyncRepository(ctx context.Context, request repository.SyncRepositoryRequestObject) (repository.SyncRepositoryResponseObject, error) {
	return adapter.server.SyncRepository(ctx, request)
}

// UpdateRepository 将 repository 的严格操作委托给对应的 Handler 实现。
func (adapter repositoryServer) UpdateRepository(ctx context.Context, request repository.UpdateRepositoryRequestObject) (repository.UpdateRepositoryResponseObject, error) {
	return adapter.server.UpdateRepository(ctx, request)
}

type serviceServer struct {
	serviceapi.UnimplementedStrictServer
	server *Server
}

// DeleteService 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) DeleteService(ctx context.Context, request serviceapi.DeleteServiceRequestObject) (serviceapi.DeleteServiceResponseObject, error) {
	return adapter.server.DeleteService(ctx, request)
}

// GetPublicService 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) GetPublicService(ctx context.Context, request serviceapi.GetPublicServiceRequestObject) (serviceapi.GetPublicServiceResponseObject, error) {
	return adapter.server.GetPublicService(ctx, request)
}

// GetService 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) GetService(ctx context.Context, request serviceapi.GetServiceRequestObject) (serviceapi.GetServiceResponseObject, error) {
	return adapter.server.GetService(ctx, request)
}

// ListRecentServices 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) ListRecentServices(ctx context.Context, request serviceapi.ListRecentServicesRequestObject) (serviceapi.ListRecentServicesResponseObject, error) {
	return adapter.server.ListRecentServices(ctx, request)
}

// UpdateService 将 service 的严格操作委托给对应的 Handler 实现。
func (adapter serviceServer) UpdateService(ctx context.Context, request serviceapi.UpdateServiceRequestObject) (serviceapi.UpdateServiceResponseObject, error) {
	return adapter.server.UpdateService(ctx, request)
}

type systemServer struct {
	system.UnimplementedStrictServer
	server *Server
}

// GetOpenApiContract 将 system 的严格操作委托给对应的 Handler 实现。
func (adapter systemServer) GetOpenApiContract(ctx context.Context, request system.GetOpenApiContractRequestObject) (system.GetOpenApiContractResponseObject, error) {
	return adapter.server.GetOpenApiContract(ctx, request)
}

// GetVersion 将 system 的严格操作委托给对应的 Handler 实现。
func (adapter systemServer) GetVersion(ctx context.Context, request system.GetVersionRequestObject) (system.GetVersionResponseObject, error) {
	return adapter.server.GetVersion(ctx, request)
}

// Healthz 将 system 的严格操作委托给对应的 Handler 实现。
func (adapter systemServer) Healthz(ctx context.Context, request system.HealthzRequestObject) (system.HealthzResponseObject, error) {
	return adapter.server.Healthz(ctx, request)
}

// Metrics 将 system 的严格操作委托给对应的 Handler 实现。
func (adapter systemServer) Metrics(ctx context.Context, request system.MetricsRequestObject) (system.MetricsResponseObject, error) {
	return adapter.server.Metrics(ctx, request)
}

// Readyz 将 system 的严格操作委托给对应的 Handler 实现。
func (adapter systemServer) Readyz(ctx context.Context, request system.ReadyzRequestObject) (system.ReadyzResponseObject, error) {
	return adapter.server.Readyz(ctx, request)
}

type tenantServer struct {
	tenant.UnimplementedStrictServer
	server *Server
}

// CreateCredential 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) CreateCredential(ctx context.Context, request tenant.CreateCredentialRequestObject) (tenant.CreateCredentialResponseObject, error) {
	return adapter.server.CreateCredential(ctx, request)
}

// CreateKnownHost 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) CreateKnownHost(ctx context.Context, request tenant.CreateKnownHostRequestObject) (tenant.CreateKnownHostResponseObject, error) {
	return adapter.server.CreateKnownHost(ctx, request)
}

// CreateToken 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) CreateToken(ctx context.Context, request tenant.CreateTokenRequestObject) (tenant.CreateTokenResponseObject, error) {
	return adapter.server.CreateToken(ctx, request)
}

// DeleteCredential 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) DeleteCredential(ctx context.Context, request tenant.DeleteCredentialRequestObject) (tenant.DeleteCredentialResponseObject, error) {
	return adapter.server.DeleteCredential(ctx, request)
}

// ListAvailableProducerProfiles 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ListAvailableProducerProfiles(ctx context.Context, request tenant.ListAvailableProducerProfilesRequestObject) (tenant.ListAvailableProducerProfilesResponseObject, error) {
	return adapter.server.ListAvailableProducerProfiles(ctx, request)
}

// ListCredentials 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ListCredentials(ctx context.Context, request tenant.ListCredentialsRequestObject) (tenant.ListCredentialsResponseObject, error) {
	return adapter.server.ListCredentials(ctx, request)
}

// ListKnownHosts 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ListKnownHosts(ctx context.Context, request tenant.ListKnownHostsRequestObject) (tenant.ListKnownHostsResponseObject, error) {
	return adapter.server.ListKnownHosts(ctx, request)
}

// ListTokens 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) ListTokens(ctx context.Context, request tenant.ListTokensRequestObject) (tenant.ListTokensResponseObject, error) {
	return adapter.server.ListTokens(ctx, request)
}

// RevokeToken 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) RevokeToken(ctx context.Context, request tenant.RevokeTokenRequestObject) (tenant.RevokeTokenResponseObject, error) {
	return adapter.server.RevokeToken(ctx, request)
}

// RotateCredential 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) RotateCredential(ctx context.Context, request tenant.RotateCredentialRequestObject) (tenant.RotateCredentialResponseObject, error) {
	return adapter.server.RotateCredential(ctx, request)
}

// TestCredential 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) TestCredential(ctx context.Context, request tenant.TestCredentialRequestObject) (tenant.TestCredentialResponseObject, error) {
	return adapter.server.TestCredential(ctx, request)
}

// UpdateCredential 将 tenant 的严格操作委托给对应的 Handler 实现。
func (adapter tenantServer) UpdateCredential(ctx context.Context, request tenant.UpdateCredentialRequestObject) (tenant.UpdateCredentialResponseObject, error) {
	return adapter.server.UpdateCredential(ctx, request)
}

type viewServer struct {
	view.UnimplementedStrictServer
	server *Server
}

// CreateSystemGroup 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) CreateSystemGroup(ctx context.Context, request view.CreateSystemGroupRequestObject) (view.CreateSystemGroupResponseObject, error) {
	return adapter.server.CreateSystemGroup(ctx, request)
}

// GetSharedView 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) GetSharedView(ctx context.Context, request view.GetSharedViewRequestObject) (view.GetSharedViewResponseObject, error) {
	return adapter.server.GetSharedView(ctx, request)
}

// PutSystemGroupMembers 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) PutSystemGroupMembers(ctx context.Context, request view.PutSystemGroupMembersRequestObject) (view.PutSystemGroupMembersResponseObject, error) {
	return adapter.server.PutSystemGroupMembers(ctx, request)
}

// ResolveView 将 view 的严格操作委托给对应的 Handler 实现。
func (adapter viewServer) ResolveView(ctx context.Context, request view.ResolveViewRequestObject) (view.ResolveViewResponseObject, error) {
	return adapter.server.ResolveView(ctx, request)
}

func registerDomainHandlers(server *Server, router chi.Router) {
	assetStrict := asset.NewStrictHandlerWithOptions(assetServer{server: server}, []asset.StrictMiddlewareFunc{
		func(next asset.StrictHandlerFunc, operationID string) asset.StrictHandlerFunc {
			return asset.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, asset.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	asset.HandlerFromMux(assetStrict, router)
	authStrict := auth.NewStrictHandlerWithOptions(authServer{server: server}, []auth.StrictMiddlewareFunc{
		func(next auth.StrictHandlerFunc, operationID string) auth.StrictHandlerFunc {
			return auth.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, auth.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	auth.HandlerFromMux(authStrict, router)
	collaborationStrict := collaboration.NewStrictHandlerWithOptions(collaborationServer{server: server}, []collaboration.StrictMiddlewareFunc{
		func(next collaboration.StrictHandlerFunc, operationID string) collaboration.StrictHandlerFunc {
			return collaboration.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, collaboration.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	collaboration.HandlerFromMux(collaborationStrict, router)
	diffStrict := diff.NewStrictHandlerWithOptions(diffServer{server: server}, []diff.StrictMiddlewareFunc{
		func(next diff.StrictHandlerFunc, operationID string) diff.StrictHandlerFunc {
			return diff.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, diff.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	diff.HandlerFromMux(diffStrict, router)
	jobStrict := job.NewStrictHandlerWithOptions(jobServer{server: server}, []job.StrictMiddlewareFunc{
		func(next job.StrictHandlerFunc, operationID string) job.StrictHandlerFunc {
			return job.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, job.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	job.HandlerFromMux(jobStrict, router)
	layerStrict := layer.NewStrictHandlerWithOptions(layerServer{server: server}, []layer.StrictMiddlewareFunc{
		func(next layer.StrictHandlerFunc, operationID string) layer.StrictHandlerFunc {
			return layer.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, layer.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	layer.HandlerFromMux(layerStrict, router)
	platformStrict := platform.NewStrictHandlerWithOptions(platformServer{server: server}, []platform.StrictMiddlewareFunc{
		func(next platform.StrictHandlerFunc, operationID string) platform.StrictHandlerFunc {
			return platform.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, platform.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	platform.HandlerFromMux(platformStrict, router)
	repositoryStrict := repository.NewStrictHandlerWithOptions(repositoryServer{server: server}, []repository.StrictMiddlewareFunc{
		func(next repository.StrictHandlerFunc, operationID string) repository.StrictHandlerFunc {
			return repository.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, repository.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	repository.HandlerFromMux(repositoryStrict, router)
	serviceStrict := serviceapi.NewStrictHandlerWithOptions(serviceServer{server: server}, []serviceapi.StrictMiddlewareFunc{
		func(next serviceapi.StrictHandlerFunc, operationID string) serviceapi.StrictHandlerFunc {
			return serviceapi.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, serviceapi.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	serviceapi.HandlerFromMux(serviceStrict, router)
	systemStrict := system.NewStrictHandlerWithOptions(systemServer{server: server}, []system.StrictMiddlewareFunc{
		func(next system.StrictHandlerFunc, operationID string) system.StrictHandlerFunc {
			return system.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, system.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	system.HandlerFromMux(systemStrict, router)
	tenantStrict := tenant.NewStrictHandlerWithOptions(tenantServer{server: server}, []tenant.StrictMiddlewareFunc{
		func(next tenant.StrictHandlerFunc, operationID string) tenant.StrictHandlerFunc {
			return tenant.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, tenant.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	tenant.HandlerFromMux(tenantStrict, router)
	viewStrict := view.NewStrictHandlerWithOptions(viewServer{server: server}, []view.StrictMiddlewareFunc{
		func(next view.StrictHandlerFunc, operationID string) view.StrictHandlerFunc {
			return view.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))
		},
	}, view.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})
	view.HandlerFromMux(viewStrict, router)
}
