// Command domainadapter generates the compatibility bridge from domain-owned
// oapi-codegen servers to the existing handler implementations.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
)

const outputPath = "internal/handler/domain_adapters.gen.go"

type domain struct {
	name         string
	packageName  string
	serverSource string
	methods      []string
}

func main() {
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() error {
	domains, err := discoverDomains()
	if err != nil {
		return err
	}
	implemented, err := implementedServerMethods()
	if err != nil {
		return err
	}
	for i := range domains {
		methods, err := strictMethods(domains[i].serverSource)
		if err != nil {
			return fmt.Errorf("load %s strict server: %w", domains[i].name, err)
		}
		for _, method := range methods {
			if implemented[method] {
				domains[i].methods = append(domains[i].methods, method)
			}
		}
		sort.Strings(domains[i].methods)
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by internal/codegen/domainadapter. DO NOT EDIT.\n\n")
	output.WriteString("package handler\n\n")
	output.WriteString("import (\n")
	output.WriteString("\t\"context\"\n\n")
	output.WriteString("\t\"github.com/go-chi/chi/v5\"\n")
	for _, domain := range domains {
		if domain.packageName == domain.name {
			fmt.Fprintf(&output, "\t\"github.com/meridian-labs/meridian/internal/generated/api/%s\"\n", domain.name)
		} else {
			fmt.Fprintf(&output, "\t%s \"github.com/meridian-labs/meridian/internal/generated/api/%s\"\n", domain.packageName, domain.name)
		}
	}
	output.WriteString(")\n\n")

	for _, domain := range domains {
		fmt.Fprintf(&output, "type %sServer struct {\n\t%s.UnimplementedStrictServer\n\tserver *Server\n}\n\n", domain.name, domain.packageName)
		for _, method := range domain.methods {
			fmt.Fprintf(&output, "func (adapter %sServer) %s(ctx context.Context, request %s.%sRequestObject) (%s.%sResponseObject, error) {\n", domain.name, method, domain.packageName, method, domain.packageName, method)
			fmt.Fprintf(&output, "\treturn adapter.server.%s(ctx, request)\n}\n\n", method)
		}
	}

	output.WriteString("func registerDomainHandlers(server *Server, router chi.Router) {\n")
	for _, domain := range domains {
		fmt.Fprintf(&output, "\t%sStrict := %s.NewStrictHandlerWithOptions(%sServer{server: server}, []%s.StrictMiddlewareFunc{\n", domain.name, domain.packageName, domain.name, domain.packageName)
		fmt.Fprintf(&output, "\t\tfunc(next %s.StrictHandlerFunc, operationID string) %s.StrictHandlerFunc {\n", domain.packageName, domain.packageName)
		fmt.Fprintf(&output, "\t\t\treturn %s.StrictHandlerFunc(server.authenticateOperation(strictHandlerFunc(next), operationID))\n\t\t},\n", domain.packageName)
		fmt.Fprintf(&output, "\t}, %s.StrictHTTPServerOptions{RequestErrorHandlerFunc: requestErrorHandler, ResponseErrorHandlerFunc: responseErrorHandler})\n", domain.packageName)
		fmt.Fprintf(&output, "\t%s.HandlerFromMux(%sStrict, router)\n", domain.packageName, domain.name)
	}
	output.WriteString("}\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return fmt.Errorf("format generated domain adapters: %w", err)
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write generated domain adapters: %w", err)
	}
	return nil
}

func discoverDomains() ([]domain, error) {
	serverSources, err := filepath.Glob("internal/generated/api/*/server.gen.go")
	if err != nil {
		return nil, fmt.Errorf("find generated domain servers: %w", err)
	}
	if len(serverSources) == 0 {
		return nil, errors.New("no generated domain servers found")
	}
	sort.Strings(serverSources)

	domains := make([]domain, 0, len(serverSources))
	for _, serverSource := range serverSources {
		packageName, err := generatedPackageName(serverSource)
		if err != nil {
			return nil, err
		}
		domains = append(domains, domain{
			name:         filepath.Base(filepath.Dir(serverSource)),
			packageName:  packageName,
			serverSource: serverSource,
		})
	}
	return domains, nil
}

func generatedPackageName(filename string) (string, error) {
	parsed, err := parser.ParseFile(token.NewFileSet(), filename, nil, parser.PackageClauseOnly)
	if err != nil {
		return "", fmt.Errorf("parse generated package %s: %w", filename, err)
	}
	return parsed.Name.Name, nil
}

func implementedServerMethods() (map[string]bool, error) {
	files := token.NewFileSet()
	packages, err := parser.ParseDir(files, "internal/handler", func(info os.FileInfo) bool {
		return filepath.Ext(info.Name()) == ".go" && filepath.Base(info.Name()) != filepath.Base(outputPath)
	}, parser.SkipObjectResolution)
	if err != nil {
		return nil, fmt.Errorf("parse handlers: %w", err)
	}
	implementation := packages["handler"]
	if implementation == nil {
		return nil, errors.New("handler package was not found")
	}
	methods := make(map[string]bool)
	for _, file := range implementation.Files {
		for _, declaration := range file.Decls {
			function, ok := declaration.(*ast.FuncDecl)
			if !ok || function.Recv == nil || len(function.Recv.List) != 1 {
				continue
			}
			pointer, ok := function.Recv.List[0].Type.(*ast.StarExpr)
			if !ok {
				continue
			}
			receiver, ok := pointer.X.(*ast.Ident)
			if ok && receiver.Name == "Server" {
				methods[function.Name.Name] = true
			}
		}
	}
	return methods, nil
}

func strictMethods(source string) ([]string, error) {
	files := token.NewFileSet()
	parsed, err := parser.ParseFile(files, source, nil, parser.SkipObjectResolution)
	if err != nil {
		return nil, err
	}
	for _, declaration := range parsed.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, specification := range general.Specs {
			typeSpecification, ok := specification.(*ast.TypeSpec)
			if !ok || typeSpecification.Name.Name != "StrictServerInterface" {
				continue
			}
			contract, ok := typeSpecification.Type.(*ast.InterfaceType)
			if !ok {
				return nil, errors.New("StrictServerInterface is not an interface")
			}
			methods := make([]string, 0, len(contract.Methods.List))
			for _, method := range contract.Methods.List {
				if len(method.Names) == 1 {
					methods = append(methods, method.Names[0].Name)
				}
			}
			return methods, nil
		}
	}
	return nil, errors.New("StrictServerInterface was not found")
}
