// Command strictstub generates an embeddable default implementation of the
// oapi-codegen StrictServerInterface.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

const (
	serverSource = "internal/generated/api/server.gen.go"
	stubOutput   = "internal/generated/api/strict_unimplemented.gen.go"
)

func main() {
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() error {
	files := token.NewFileSet()
	parsed, err := parser.ParseFile(files, serverSource, nil, parser.SkipObjectResolution)
	if err != nil {
		return fmt.Errorf("parse strict server source: %w", err)
	}
	methods, err := strictMethods(parsed)
	if err != nil {
		return err
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by internal/codegen/strictstub. DO NOT EDIT.\n\n")
	output.WriteString("package api\n\n")
	output.WriteString("import (\n\t\"context\"\n\t\"errors\"\n)\n\n")
	output.WriteString("// ErrStrictOperationNotImplemented indicates that an OpenAPI operation has no milestone implementation yet.\n")
	output.WriteString("var ErrStrictOperationNotImplemented = errors.New(\"OpenAPI operation is not implemented\")\n\n")
	output.WriteString("// UnimplementedStrictServer provides explicit defaults for every generated strict operation.\n")
	output.WriteString("// Embed it by value and override only the operations owned by the current milestone.\n")
	output.WriteString("type UnimplementedStrictServer struct{}\n\n")
	for _, method := range methods {
		var signature bytes.Buffer
		if err := format.Node(&signature, files, method.Type); err != nil {
			return fmt.Errorf("format %s signature: %w", method.Names[0].Name, err)
		}
		name := method.Names[0].Name
		output.WriteString("// " + name + " returns ErrStrictOperationNotImplemented until its milestone is implemented.\n")
		output.WriteString("func (UnimplementedStrictServer) " + name)
		output.WriteString(strings.TrimPrefix(signature.String(), "func"))
		output.WriteString(" {\n\treturn nil, ErrStrictOperationNotImplemented\n}\n\n")
	}

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return fmt.Errorf("format generated strict stub: %w", err)
	}
	if err := os.WriteFile(stubOutput, formatted, 0o644); err != nil {
		return fmt.Errorf("write generated strict stub: %w", err)
	}
	return nil
}

func strictMethods(file *ast.File) ([]*ast.Field, error) {
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, specification := range general.Specs {
			typeSpecification, ok := specification.(*ast.TypeSpec)
			if !ok || typeSpecification.Name.Name != "StrictServerInterface" {
				continue
			}
			contract, ok := typeSpecification.Type.(*ast.InterfaceType)
			if !ok {
				return nil, errors.New("StrictServerInterface is not an interface")
			}
			return contract.Methods.List, nil
		}
	}
	return nil, errors.New("StrictServerInterface was not found")
}
