// Command strictstub 生成可嵌入的 oapi-codegen StrictServerInterface 默认实现。
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type target struct {
	packageName  string
	serverSource string
	stubOutput   string
}

func main() {
	targets, err := discoverTargets()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	for _, target := range targets {
		if err := generate(target); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
}

func generate(target target) error {
	files := token.NewFileSet()
	parsed, err := parser.ParseFile(files, target.serverSource, nil, parser.SkipObjectResolution)
	if err != nil {
		return fmt.Errorf("parse strict server source: %w", err)
	}
	methods, err := strictMethods(parsed)
	if err != nil {
		return err
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by internal/codegen/strictstub. DO NOT EDIT.\n\n")
	output.WriteString("package " + target.packageName + "\n\n")
	output.WriteString("import (\n\t\"context\"\n\n\trootapi \"github.com/meridian-labs/meridian/internal/generated/api\"\n)\n\n")
	output.WriteString("// UnimplementedStrictServer 为每个生成的严格操作提供显式默认实现。\n")
	output.WriteString("// 以值方式嵌入，并只覆写当前里程碑拥有的操作。\n")
	output.WriteString("type UnimplementedStrictServer struct{}\n\n")
	for _, method := range methods {
		var signature bytes.Buffer
		if err := format.Node(&signature, files, method.Type); err != nil {
			return fmt.Errorf("format %s signature: %w", method.Names[0].Name, err)
		}
		name := method.Names[0].Name
		output.WriteString("// " + name + " 在其里程碑实现之前返回 ErrStrictOperationNotImplemented。\n")
		output.WriteString("func (UnimplementedStrictServer) " + name)
		output.WriteString(strings.TrimPrefix(signature.String(), "func"))
		output.WriteString(" {\n\treturn nil, rootapi.ErrStrictOperationNotImplemented\n}\n\n")
	}

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return fmt.Errorf("format generated strict stub: %w", err)
	}
	if err := os.WriteFile(target.stubOutput, formatted, 0o644); err != nil {
		return fmt.Errorf("write generated strict stub: %w", err)
	}
	return nil
}

func discoverTargets() ([]target, error) {
	serverSources, err := filepath.Glob("internal/generated/api/*/server.gen.go")
	if err != nil {
		return nil, fmt.Errorf("find generated domain servers: %w", err)
	}
	if len(serverSources) == 0 {
		return nil, errors.New("no generated domain servers found")
	}
	sort.Strings(serverSources)

	targets := make([]target, 0, len(serverSources))
	for _, serverSource := range serverSources {
		packageName, err := generatedPackageName(serverSource)
		if err != nil {
			return nil, err
		}
		domainDirectory := filepath.Dir(serverSource)
		targets = append(targets, target{
			packageName:  packageName,
			serverSource: serverSource,
			stubOutput:   filepath.Join(domainDirectory, "strict_unimplemented.gen.go"),
		})
	}
	return targets, nil
}

func generatedPackageName(filename string) (string, error) {
	parsed, err := parser.ParseFile(token.NewFileSet(), filename, nil, parser.PackageClauseOnly)
	if err != nil {
		return "", fmt.Errorf("parse generated package %s: %w", filename, err)
	}
	return parsed.Name.Name, nil
}

func strictMethods(file *ast.File) ([]*ast.Field, error) {
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, specification := range general.Specs {
			typeSpecification, ok := specification.(*ast.TypeSpec)
			if !ok || typeSpecification.Name.Name != "StrictServerInterface" {
				continue
			}
			contract, ok := typeSpecification.Type.(*ast.InterfaceType)
			if !ok {
				return nil, errors.New("StrictServerInterface is not an interface")
			}
			return contract.Methods.List, nil
		}
	}
	return nil, errors.New("StrictServerInterface was not found")
}
